### ISSUE TITLE
Could we add Grey Out function to layers when zoom level is outside of Visibility Range?

### ISSUE THREAD

**Issue by dwoodinnovate** [Innovate-Inc/GroupedLayerListWidget#29]
I wondered if we could enhance this widget to function similarly to the original Layer List widget so that when a layer that has a Visibility Range set the layer is greyed out so you know that layer isn't visible at that zoom level.

![image](https://user-images.githubusercontent.com/11931923/88345306-8dbbb200-ccfa-11ea-9780-6ba5ad5c9161.png)

![image](https://user-images.githubusercontent.com/11931923/88345366-adeb7100-ccfa-11ea-9ae1-dad52abf76a1.png)

**Comment by David-Yarnell** [comment]
@dwoodinnovate yes, that's a great idea and would be a good enhancement to the widget.

**Comment by David-Yarnell** [comment]
@dwoodinnovate This has been completed
