### ISSUE TITLE
Indicate which groups have layers turned on

### ISSUE THREAD

**Issue by abprins** [Innovate-Inc/GroupedLayerListWidget#36]
Can we somehow indicate which groups contain layers that are turned on? One comment I've received is that it's easier to quickly spot which layers are turned on in the original layer list.

Can we maybe bold the group names that contain active layers? Perhaps with a small indicator showing how many are on?

Open to other suggestions for differentiating groups with layers on vs. off.

**Comment by David-Yarnell** [comment]
Yes, we should be able to add that functionality. I think the most common functionality like this is to grey out layers that are not visible.

**Comment by abprins** [comment]
> grey out layers that are not visible.

At the group level?

The big thing is to be able to see which groups have layers turned on without needing to expand any of the groups. This is probably more complicated than it sounds, since many/most groups will have at least one layer turned on, hence why it might be helpful to build in an indicator next to the group name that shows how many nested layers are turned on.

**Comment by abprins** [comment]
Just got some more clarification from CH on what she's thinking for this. She's imagining having an indicator in a right-justified column that shows how many layers in that group are turned on, out of the total number of layers in that group (#/#).

Like this:
![image](https://user-images.githubusercontent.com/62261480/97460310-e00ffe80-18f9-11eb-87d3-776080e0ebd6.png)
