### ISSUE TITLE
On/Off Toggle broken for "Facilities - NPL" group

### ISSUE THREAD

**Issue by abprins** [Innovate-Inc/GroupedLayerListWidget#37]
Toggle shows as switched on:
![layerlist_npl_on](https://user-images.githubusercontent.com/62261480/97363621-1a2cc200-1860-11eb-9549-2893d10a3932.jpg)

even when layer is turned off:
![layerlist_npl_off](https://user-images.githubusercontent.com/62261480/97363738-421c2580-1860-11eb-99f4-71e733d6e92f.jpg)

**Comment by David-Yarnell** [comment]
@aprins-innovate this has occurred because the R9 NLP Points and R9 NLP Polygon layers were added to multiple groups within the widget (Facilities -NLP and  Facilities - NPDES). I confirmed this with @dwoodinnovate.
